name: Release Negev Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o negev-linux-amd64 -v
        env:
          CGO_ENABLED: 0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: negev-linux-amd64
          path: negev-linux-amd64

  build-windows:
    name: Build Windows Binary
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build binary
        shell: powershell
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          $env:CGO_ENABLED = "0"
          go build -o negev-windows-amd64.exe -v

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: negev-windows-amd64.exe
          path: negev-windows-amd64.exe

  release:
    name: Create Release
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Set tag
        run: |
          echo "TAG=${{ inputs.version }}" >> $GITHUB_ENV
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/negev-linux-amd64/negev-linux-amd64
            artifacts/negev-windows-amd64.exe/negev-windows-amd64.exe
          name: "Negev ${{ inputs.version }}"
          tag_name: ${{ inputs.version }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}